<a href="https://colab.research.google.com/github/nkharlamova/ML/blob/main/HW_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import pi

**1. Load the dataset**

In [ ]:
data_set = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=float, delimiter=',', usecols=(0,1,2,3))

**2. Convert the remaining columns into a 2D array (or ensure that it is already a 2D array)**

In [ ]:
# 2 Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)

print('Dimensions: ', data_set.ndim)
print('Shape: ', data_set.shape)
print('Type: ', type(data_set))
print('Size: ', data_set.size)

Dimensions:  2
Shape:  (150, 4)
Type:  <class 'numpy.ndarray'>
Size:  600


**3. Calculate the mean, median, and standard deviation for the first column**

In [ ]:
# 3 Порахувати mean, median, standard deviation для 1-ї колонки

data_mean = np.mean(data_set[:, 0])
data_med = np.median(data_set[:, 0])
data_stand = np.std(data_set[:, 0])
print('Mean Deviation: ', data_mean)
print('Median Deviation: ', data_med)
print('Standard Deviation: ', data_stand)

Mean Deviation:  5.843333333333334
Median Deviation:  5.8
Standard Deviation:  0.8253012917851409


**4. Insert 20 np.nan values at random positions in an array (using a regular random function might result in overlapping positions, so find a solution that guarantees 20 unique positions)**

In [ ]:
# 4 Вставити 20 значень np.nan на випадкові позиції в масиві
# (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)

np.random.seed(42)
n=20
index_nan = np.random.choice(data_set.size, n, replace=False)
data_set.ravel()[index_nan] = np.nan
print(data_set)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 nan 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 nan 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 nan]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 nan nan 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 nan 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 nan nan 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 nan 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 nan 1.4 0.3]
 [nan 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

**5. Find the positions of the inserted np.nan values in the first column**

In [ ]:
# 5 Знайти позиції вставлених значень np.nan в 1-й колонці

count_nan = np.count_nonzero(np.isnan(data_set[:, 0]))
print('Count NaN in the 1st Column: ', count_nan)

np.isnan(data_set[:, 0])
index_gt5 = np.where(np.isnan(data_set[:, 0]))
print("Positions where NaN: ", index_gt5)

count_n_all = np.count_nonzero(np.isnan(data_set))
print('Count NaN in the 1st Column: ', count_n_all)

Count NaN in the 1st Column:  4
Positions where NaN:  (array([ 46,  53,  71, 147]),)
Count NaN in the 1st Column:  20


**6. Filter the array with the condition: values in the 3rd column > 1.5 and values in the 1st column < 5.0 (store in another variable)**

In [ ]:
# 6 Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0 (зберегти у іншу змінну)

filter_data_set = data_set[(data_set[:, 2] > 1.5 ) & (data_set[:, 0] < 5.0 )]
print(filter_data_set)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


**7. Replace all np.nan values with 0**

In [ ]:
# 7 Замінити всі значення np.nan на 0

data_set[np.isnan(data_set)] = 0

# view updated array
print(data_set)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 0.  0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0. ]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 0.  0.  0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 0.  0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 0.  0.  0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 0.  1.4 0.3]
 [0.  3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

**8. Count all unique values in the array and display them along with their counts**

In [ ]:
# 8 Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю

uniqs, counts = np.unique(data_set, return_counts=True)
print("Unique values : ", uniqs)
print("Counts       : ", counts)

Unique values :  [0.  0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.
 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6
 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4
 7.6 7.7 7.9]
Counts       :  [20  5 28  7  7  1  1  8  4  7 19 20 22 10  6 12  7  7  6  5 11  6 11  4
  9 14 10 26 11 13  8 12  7  4  4  5  5  6  4  5  3  8  9  6  7  9 11 14
 16  6  3  8  9 12 11 10  5  8  8  4 10  8  4  3 10  3  5  1  1  3  1  1
  1  4  1]


**9. Split the array vertically into 2 equal parts (each array should have 4 columns, without using absolute numbers)**

In [ ]:
# 9 Розбити масив по вертикалі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)

split_data_set_1, split_data_set_2 = np.vsplit(data_set,2)
print(split_data_set_1.shape, split_data_set_2.shape)

(75, 4) (75, 4)


**10. Sort both arrays by the 1st column: the first array in ascending order, and the second array in descending order**

In [ ]:
# 10 Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням

# sort by the 1st column in ascending order
sort_index_1 = split_data_set_1[:, 0].argsort()
data_set_1_sort = split_data_set_1[sort_index_1]

# sort by the 1st column in descending order
sort_index_2 = split_data_set_2[:, 0].argsort()[::-1]

data_set_2_sort = split_data_set_2[sort_index_2]

# print(sort_index_1)
# print(sort_index_2)
print(data_set_1_sort, data_set_2_sort)

[[0.  3.8 1.6 0.2]
 [0.  2.3 4.  1.3]
 [0.  2.8 4.  1.3]
 [4.3 3.  1.1 0. ]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.4 1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.7 3.2 0.  0.2]
 [4.8 0.  1.4 0.3]
 [4.8 3.4 1.9 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.5 1.6 0.6]
 [5.  3.3 1.4 0.2]
 [5.  2.  3.5 1. ]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.5 1.3 0.3]
 [5.  3.4 0.  0.2]
 [5.  3.6 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 0.  0.  0.3]
 [5.1 3.3 1.7 0.5]
 [5.1 3.7 0.  0.4]
 [5.1 3.5 1.4 0.3]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.2 0.  0.  0.2]
 [5.2 2.7 3.9 1.4]
 [5.3 3.7 1.5 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.5 3.5 1.3 0.2]
 [5.5 4.2 1.4 0.2]
 [5.6 2.9 3.

**11. Merge both arrays into one single array**

In [ ]:
# 11 Зібрати обидва массиви в одне ціле

data_set_new = np.vstack([data_set_1_sort,data_set_2_sort])
print(data_set_new.shape)

#view updated array
#print(data_set_new)

(150, 4)


**12. Find the most frequently occurring value in the array**

In [ ]:
# 12 Знайти найбільш часто повторюване значення в массиві

flat_array = data_set_new.flatten()

most_frequent_val, c_index = np.unique(flat_array, return_inverse=True)
most_frequent_val[np.argmax(np.bincount(c_index))]

0.2

**13. Write a function that multiplies all values in a column that are less than the column's average by 2, and divides all other values by 4**

In [ ]:
# 13 Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.

def modify_data_in_column(column):

    column_mean = np.mean(column)
    column = np.where(column < column_mean, column * 2, column / 4)

    return column


**14. Apply the obtained function to the 3rd column**

In [ ]:
# 14 Застосувати отриману функцію до 3-ї колонки

modify_data_in_column(data_set[:, 2])


array([2.8  , 2.8  , 0.   , 3.   , 2.8  , 3.4  , 2.8  , 0.   , 2.8  ,
       3.   , 3.   , 3.2  , 2.8  , 2.2  , 2.4  , 3.   , 2.6  , 2.8  ,
       3.4  , 0.   , 3.4  , 0.   , 2.   , 3.4  , 3.8  , 3.2  , 3.2  ,
       0.   , 2.8  , 0.   , 3.2  , 3.   , 3.   , 2.8  , 3.   , 2.4  ,
       2.6  , 3.   , 2.6  , 3.   , 2.6  , 2.6  , 2.6  , 3.2  , 3.8  ,
       2.8  , 3.2  , 2.8  , 3.   , 2.8  , 1.175, 1.125, 1.225, 1.   ,
       1.15 , 1.125, 1.175, 6.6  , 0.   , 0.975, 7.   , 1.05 , 1.   ,
       1.175, 7.2  , 1.1  , 1.125, 1.025, 1.125, 0.975, 1.2  , 1.   ,
       1.225, 1.175, 1.075, 1.1  , 1.2  , 1.25 , 1.125, 7.   , 0.95 ,
       0.925, 0.975, 1.275, 1.125, 1.125, 1.175, 1.1  , 1.025, 1.   ,
       1.1  , 1.15 , 1.   , 6.6  , 1.05 , 1.05 , 1.05 , 1.075, 6.   ,
       1.025, 1.5  , 1.275, 1.475, 1.4  , 1.45 , 1.65 , 1.125, 1.575,
       1.45 , 1.525, 1.275, 1.325, 1.375, 1.25 , 1.275, 1.325, 1.375,
       1.675, 1.725, 1.25 , 1.425, 1.225, 1.675, 1.225, 1.425, 1.5  ,
       1.2  , 1.225,